// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2bLBB6pknqaR_X7MsNvkIWfwFJMkIAWk',
    appId: '1:856485694389:web:ee2960cdcc962efe8327fc',
    messagingSenderId: '856485694389',
    projectId: 'ant-hill-adf22',
    authDomain: 'ant-hill-adf22.firebaseapp.com',
    storageBucket: 'ant-hill-adf22.appspot.com',
    measurementId: 'G-R1RTXWSZZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtkHtx7yMP16WMe6IocS_f8RtkyEGXVew',
    appId: '1:856485694389:android:ba285633b6cc67b08327fc',
    messagingSenderId: '856485694389',
    projectId: 'ant-hill-adf22',
    storageBucket: 'ant-hill-adf22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT2-uIjhHdOVwtQnkcnD7obX2uJmoZVQM',
    appId: '1:856485694389:ios:8caabfc6fafeaceb8327fc',
    messagingSenderId: '856485694389',
    projectId: 'ant-hill-adf22',
    storageBucket: 'ant-hill-adf22.appspot.com',
    iosClientId: '856485694389-ol0vr4soedo7uka8ldojr5q06g4eq70u.apps.googleusercontent.com',
    iosBundleId: 'com.example.antHill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT2-uIjhHdOVwtQnkcnD7obX2uJmoZVQM',
    appId: '1:856485694389:ios:8caabfc6fafeaceb8327fc',
    messagingSenderId: '856485694389',
    projectId: 'ant-hill-adf22',
    storageBucket: 'ant-hill-adf22.appspot.com',
    iosClientId: '856485694389-ol0vr4soedo7uka8ldojr5q06g4eq70u.apps.googleusercontent.com',
    iosBundleId: 'com.example.antHill',
  );
}
